---
- hosts: localhost
  connection: local
  become: false
  tasks:
    - name: Read users from CSV file and return a dictionary
      community.general.read_csv:
        path: users.csv
        key: name
      register: users
    - ansible.builtin.debug:
        msg: 'User {{ users.dict.dag.name }} has UID {{ users.dict.dag.uid }} and GID {{ users.dict.dag.gid }}'
    - name: Read users from CSV file and return a list
      community.general.read_csv:
        path: users.csv
      register: users
    - ansible.builtin.debug:
        msg: 'User {{ users.list.1.name }} has UID {{ users.list.1.uid }} and GID {{ users.list.1.gid }}'

    # Example CSV file without header and semi-colon delimiter
    #
    #   dag;500;500
    #   jeroen;501;500
    # Read a CSV file without headers
#     - name: Read users from CSV file and return a list
#       community.general.read_csv:
#         path: users.csv
#         fieldnames: name,uid,gid
#         delimiter: ';'
#       register: users
#       delegate_to: localhost
