---
- hosts: localhost
  connection: local
  become: false
  tasks:
    - name: Read users from CSV file and return a dictionary
      community.general.read_csv:
        path: users.csv
        key: name
      register: users
    - ansible.builtin.debug:
        msg: 'User {{ users.dict.dag.name }} has UID {{ users.dict.dag.uid }} and GID {{ users.dict.dag.gid }}'
    - name: Read users from CSV file and return a list
      community.general.read_csv:
        path: users.csv
      register: users
    - ansible.builtin.debug:
        msg: 'User {{ users.list.1.name }} has UID {{ users.list.1.uid }} and GID {{ users.list.1.gid }}'
    - name: Unarchive a file that needs to be downloaded (added in 2.0)
      ansible.builtin.unarchive:
        src: https://releases.ansible.com/ansible-tower/setup_openshift/ansible-tower-openshift-setup-3.8.3-1.tar.gz
        dest: /tmp
        remote_src: yes
    - name: Verify unarchive
      shell: |
        ls -al /tmp
      register: output
    - name: Verify parameters passed in
      debug:
        msg: "Additional arguments: {{ cluster_name | default('undefined') }}"
     
